tags:
  - name: "Product"
    description: "Operaciones relacionadas con productos"

/api/products:
  get:
    tags:
      - Product
    summary: Obtener lista de productos
    responses:
      200:
        description: Lista de productos
        schema:
         # $ref: '#/definitions/ProductListResponse'
  post:
    tags:
      - Product
    summary: Crear un nuevo producto
    requestBody:
      description: Detalles del nuevo producto
      required: true
      content:
        multipart/form-data:
          schema:
            $ref: '#/definitions/CreateProductRequest'
    responses:
      200:
        description: Producto creado exitosamente
        schema:
          $ref: '#/definitions/ProductDetailsResponse'
/api/products/{pid}:
  get:
    tags:
      - Product
    summary: Obtener detalles de un producto por ID
    parameters:
      - name: pid
        in: path
        required: true
        type: string
        description: ID del producto
    responses:
      200:
        description: Detalles del producto
        schema:
          $ref: '#/definitions/ProductDetailsResponse'
  put:
    tags:
      - Product
    summary: Actualizar detalles de un producto por ID
    parameters:
      - name: pid
        in: path
        required: true
        type: string
        description: ID del producto
    requestBody:
      description: Detalles actualizados del producto
      required: true
      content:
        multipart/form-data:
          schema:
            $ref: '#/definitions/UpdateProductRequest'
    responses:
      200:
        description: Detalles del producto actualizados exitosamente
        schema:
          $ref: '#/definitions/ProductDetailsResponse'
  delete:
    tags:
      - Product
    summary: Eliminar un producto por ID
    parameters:
      - name: pid
        in: path
        required: true
        type: string
        description: ID del producto a eliminar
    responses:
      200:
        description: Producto eliminado exitosamente
        schema:
          $ref: '#/definitions/DeleteProductResponse'

definitions:
  CartProductListResponse:
    type: object
    properties:
      status:
        type: string
        example: success
      payload:
        type: array
        items:
          $ref: '#/definitions/ProductDetails'
      totalDocs:
        type: integer
        example: 7
      limit:
        type: integer
        example: 10
      totalPages:
        type: integer
        example: 1
      page:
        type: integer
        example: 1
      pagingCounter:
        type: integer
        example: 1
      hasPrevPage:
        type: boolean
        example: false
      hasNextPage:
        type: boolean
        example: false
      prevPage:
        type: null
      nextPage:
        type: null

    ProductDetails:
      type: object
      properties:
        _id:
          type: string
          example: '652d699848399856ada1d63a'
        title:
          type: string
          example: 'Sonor SQ2'
        description:
          type: string
          example: 'Rock pro'
        code:
          type: string
          example: 'sdqwecc'
        price:
          type: number
          example: 1980
        status:
          type: boolean
          example: true
        stock:
          type: integer
          example: 90
        category:
          type: string
          example: 'drum'
        thumbnail:
          type: array
          items:
            type: string
            example: 'D:\\CURSOS\\full-stack-coderhouse-c43395\\src\\public\\thumbnails\\1697263173794-1697250115527-1693450953712-1690072626956-sq2.jpg'
        createdAt:
          type: string
          format: date-time
          example: '2023-10-16T16:49:28.642Z'
        updatedAt:
          type: string
          format: date-time
          example: '2023-10-29T15:24:26.075Z'
        __v:
          type: integer
          example: 0
  ProductDetails:
    type: object
    properties:
      _id:
        type: string
        example: '652d699848399856ada1d63a'
      title:
        type: string
        example: 'Sonor SQ2'
      description:
        type: string
        example: 'Rock pro'
      code:
        type: string
        example: 'sdqwecc'
      price:
        type: number
        example: 1980
      status:
        type: boolean
        example: true
      stock:
        type: integer
        example: 90
      category:
        type: string
        example: 'drum'
      thumbnail:
        type: array
        items:
          type: string
          example: 'D:\\CURSOS\\full-stack-coderhouse-c43395\\src\\public\\thumbnails\\1697263173794-1697250115527-1693450953712-1690072626956-sq2.jpg'
      createdAt:
        type: string
        format: date-time
        example: '2023-10-16T16:49:28.642Z'
      updatedAt:
        type: string
        format: date-time
        example: '2023-10-29T15:24:26.075Z'
      __v:
        type: integer
        example: 0
  ProductDetailsResponse:
    type: object
    properties:
      status:
        type: string
        example: success
      payload:
        type: array
        items:
          $ref: '#/definitions/ProductDetails'
      totalDocs:
        type: integer
        example: 7
      limit:
        type: integer
        example: 1
      totalPages:
        type: integer
        example: 7
      page:
        type: integer
        example: 1
      pagingCounter:
        type: integer
        example: 1
      hasPrevPage:
        type: boolean
        example: false
      hasNextPage:
        type: boolean
        example: true
      prevPage:
        type: null
      nextPage:
        type: integer
        example: 2

    ProductDetails:
      type: object
      properties:
        _id:
          type: string
          example: '652d699848399856ada1d63a'
        title:
          type: string
          example: 'Sonor SQ2'
        description:
          type: string
          example: 'Rock pro'
        code:
          type: string
          example: 'sdqwecc'
        price:
          type: number
          example: 1980
        status:
          type: boolean
          example: true
        stock:
          type: integer
          example: 90
        category:
          type: string
          example: 'drum'
        thumbnail:
          type: array
          items:
            type: string
            example: 'D:\\CURSOS\\full-stack-coderhouse-c43395\\src\\public\\thumbnails\\1697263173794-1697250115527-1693450953712-1690072626956-sq2.jpg'
        createdAt:
          type: string
          format: date-time
          example: '2023-10-16T16:49:28.642Z'
        updatedAt:
          type: string
          format: date-time
          example: '2023-10-29T15:24:26.075Z'
        __v:
          type: integer
          example: 0
  UpdateProductRequest:
    type: object
    required:
      - title
      - description
      - code
      - price
      - status
      - stock
      - category
      - thumbnails
    properties:
      title:
        type: string
      description:
        type: string
      code:
        type: string
      price:
        type: number
      status:
        type: boolean
      stock:
        type: integer
      category:
        type: string
      thumbnails:
        type: string
        format: binary

    ProductDetailsResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        payload:
          $ref: '#/definitions/ProductDetails'
        totalDocs:
          type: integer
          example: 1
        limit:
          type: integer
          example: 1
        totalPages:
          type: integer
          example: 1
        page:
          type: integer
          example: 1
        pagingCounter:
          type: integer
          example: 1
        hasPrevPage:
          type: boolean
          example: false
        hasNextPage:
          type: boolean
          example: false
        prevPage:
          type: null
        nextPage:
          type: null

    ProductDetails:
      type: object
      properties:
        _id:
          type: string
          example: '652d699848399856ada1d63a'
        title:
          type: string
          example: 'Sonor SQ2'
        description:
          type: string
          example: 'Rock pro'
        code:
          type: string
          example: 'sdqwecc'
        price:
          type: number
          example: 1980
        status:
          type: boolean
          example: true
        stock:
          type: integer
          example: 90
        category:
          type: string
          example: 'drum'
        thumbnail:
          type: array
          items:
            type: string
            example: 'D:\\CURSOS\\full-stack-coderhouse-c43395\\src\\public\\thumbnails\\1697263173794-1697250115527-1693450953712-1690072626956-sq2.jpg'
        createdAt:
          type: string
          format: date-time
          example: '2023-10-16T16:49:28.642Z'
        updatedAt:
          type: string
          format: date-time
          example: '2023-10-29T15:24:26.075Z'
        __v:
          type: integer
          example: 0
  CreateProductRequest:
    type: object
    required:
      - title
      - description
      - code
      - price
      - status
      - stock
      - category
      - thumbnails
    properties:
      title:
        type: string
      description:
        type: string
      code:
        type: string
      price:
        type: number
      status:
        type: boolean
      stock:
        type: integer
      category:
        type: string
      thumbnails:
        type: string
        format: binary

    ProductDetailsResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        payload:
          $ref: '#/definitions/ProductDetails'
        totalDocs:
          type: integer
          example: 1
        limit:
          type: integer
          example: 1
        totalPages:
          type: integer
          example: 1
        page:
          type: integer
          example: 1
        pagingCounter:
          type: integer
          example: 1
        hasPrevPage:
          type: boolean
          example: false
        hasNextPage:
          type: boolean
          example: false
        prevPage:
          type: null
        nextPage:
          type: null

    ProductDetails:
      type: object
      properties:
        _id:
          type: string
          example: '652d699848399856ada1d63a'
        title:
          type: string
          example: 'Sonor SQ2'
        description:
          type: string
          example: 'Rock pro'
        code:
          type: string
          example: 'sdqwecc'
        price:
          type: number
          example: 1980
        status:
          type: boolean
          example: true
        stock:
          type: integer
          example: 90
        category:
          type: string
          example: 'drum'
        thumbnail:
          type: array
          items:
            type: string
            example: 'D:\\CURSOS\\full-stack-coderhouse-c43395\\src\\public\\thumbnails\\1697263173794-1697250115527-1693450953712-1690072626956-sq2.jpg'
        createdAt:
          type: string
          format: date-time
          example: '2023-10-16T16:49:28.642Z'
        updatedAt:
          type: string
          format: date-time
          example: '2023-10-29T15:24:26.075Z'
        __v:
          type: integer
          example: 0
  DeleteProductResponse:
    type: object
    properties:
      status:
        type: string
        example: success
      message:
        type: string
        example: Producto eliminado exitosamente